server:
  port: 8761

spring:
  profiles: peer1
eureka:
  instance:
    ipAddress: 127.0.0.1
    preferIpAddress: true
    hostname: peer1
  client:
    serviceUrl:
      defaultZone: http://peer2:8769/eureka/